const KidsCollection = [
  {
    id: "101",
    image: "https://picsum.photos/250/320?random=101",
    name: "Urban Street Jacket #101",
    price: 92.17,
    description:
      "Stylish jacket for modern city living, featuring a lightweight design.",
  },
  {
    id: "102",
    image: "https://picsum.photos/250/320?random=102",
    name: "Casual Cotton Shirt #102",
    price: 39.24,
    description: "Soft cotton shirt perfect for relaxed occasions and comfort.",
  },
  {
    id: "103",
    image: "https://picsum.photos/250/320?random=103",
    name: "Denim Jeans Classic #103",
    price: 74.85,
    description: "Classic denim jeans that never go out of style.",
  },
  {
    id: "104",
    image: "https://picsum.photos/250/320?random=104",
    name: "Vintage Leather Boots #104",
    price: 98.41,
    description: "Timeless leather boots crafted for durability and fashion.",
  },
  {
    id: "105",
    image: "https://picsum.photos/250/320?random=105",
    name: "Graphic Print Hoodie #105",
    price: 59.98,
    description: "Cool hoodie with custom graphic design for a bold statement.",
  },
  {
    id: "106",
    image: "https://picsum.photos/250/320?random=106",
    name: "Slim Fit Trousers #106",
    price: 65.11,
    description:
      "Sharp-looking slim trousers suitable for formal and smart-casual use.",
  },
  {
    id: "107",
    image: "https://picsum.photos/250/320?random=107",
    name: "Basic Crewneck Tee #107",
    price: 22.35,
    description: "Essential everyday tee made with breathable fabric.",
  },
  {
    id: "108",
    image: "https://picsum.photos/250/320?random=108",
    name: "Athletic Joggers #108",
    price: 43.77,
    description: "Joggers designed for peak performance and relaxation.",
  },
  {
    id: "109",
    image: "https://picsum.photos/250/320?random=109",
    name: "Wool Blend Coat #109",
    price: 89.56,
    description: "Warm and classy wool coat for cold weather styling.",
  },
  {
    id: "110",
    image: "https://picsum.photos/250/320?random=110",
    name: "Canvas Sneakers #110",
    price: 52.73,
    description:
      "Durable sneakers with a classic canvas upper and rubber sole.",
  },
  {
    id: "111",
    image: "https://picsum.photos/250/320?random=111",
    name: "Urban Street Jacket #111",
    price: 90.66,
    description: "A sharp jacket to elevate your city style game.",
  },
  {
    id: "112",
    image: "https://picsum.photos/250/320?random=112",
    name: "Casual Cotton Shirt #112",
    price: 42.95,
    description: "Classic cotton button-down shirt for any casual outing.",
  },
  {
    id: "113",
    image: "https://picsum.photos/250/320?random=113",
    name: "Denim Jeans Classic #113",
    price: 69.34,
    description: "Comfort-fit jeans with authentic denim finish.",
  },
  {
    id: "114",
    image: "https://picsum.photos/250/320?random=114",
    name: "Vintage Leather Boots #114",
    price: 104.28,
    description: "Durable and fashionable boots for all adventures.",
  },
  {
    id: "115",
    image: "https://picsum.photos/250/320?random=115",
    name: "Graphic Print Hoodie #115",
    price: 48.83,
    description: "Bold hoodie that makes a statement on any street.",
  },
  {
    id: "116",
    image: "https://picsum.photos/250/320?random=116",
    name: "Slim Fit Trousers #116",
    price: 58.12,
    description: "Refined and comfortable trousers for daily wear.",
  },
  {
    id: "117",
    image: "https://picsum.photos/250/320?random=117",
    name: "Basic Crewneck Tee #117",
    price: 28.48,
    description: "Classic tee that pairs with everything in your closet.",
  },
  {
    id: "118",
    image: "https://picsum.photos/250/320?random=118",
    name: "Athletic Joggers #118",
    price: 36.19,
    description: "Perfect joggers for gym or chill sessions.",
  },
  {
    id: "119",
    image: "https://picsum.photos/250/320?random=119",
    name: "Wool Blend Coat #119",
    price: 91.87,
    description: "Formal wool coat with modern cut and warmth.",
  },
  {
    id: "120",
    image: "https://picsum.photos/250/320?random=120",
    name: "Canvas Sneakers #120",
    price: 47.5,
    description: "Versatile sneakers with breathable comfort.",
  },
];

export default KidsCollection;
